-- MargAI Ghost Tutor pilot: institutes, uploads, query_logs with RLS.
-- Run in Supabase SQL Editor or via: supabase db push

-- Institutes: one row per coaching center; id used as Pinecone namespace.
CREATE TABLE IF NOT EXISTS institutes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       TEXT NOT NULL UNIQUE,
  email_for_report TEXT,
  ta_telegram_id   TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Uploads: track PDF ingestion per institute (audit trail, status).
CREATE TABLE IF NOT EXISTS uploads (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  institute_id BIGINT NOT NULL REFERENCES institutes(id) ON DELETE CASCADE,
  file_path    TEXT,
  filename    TEXT,
  status       TEXT NOT NULL DEFAULT 'processing' CHECK (status IN ('processing', 'completed', 'failed')),
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_uploads_institute_created ON uploads(institute_id, created_at DESC);

-- Query logs: every row linked to an institute (student messages and RAG replies).
CREATE TABLE IF NOT EXISTS query_logs (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  institute_id        BIGINT NOT NULL REFERENCES institutes(id) ON DELETE CASCADE,
  student_telegram_id TEXT,
  student_name        TEXT,
  timestamp           TIMESTAMPTZ DEFAULT NOW(),
  query_text          TEXT,
  is_photo            BOOLEAN DEFAULT FALSE,
  escalated           BOOLEAN DEFAULT FALSE,
  clarification_sent  BOOLEAN DEFAULT FALSE,
  replied_at          TIMESTAMPTZ,
  status              TEXT
);

CREATE INDEX IF NOT EXISTS idx_query_logs_institute_timestamp ON query_logs(institute_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_query_logs_student ON query_logs(student_telegram_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_query_logs_replied ON query_logs(replied_at) WHERE replied_at IS NULL;

-- RLS: enable on institutes and query_logs so anon key only sees rows for its institute.
ALTER TABLE institutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE uploads  ENABLE ROW LEVEL SECURITY;
ALTER TABLE query_logs ENABLE ROW LEVEL SECURITY;

-- Pilot: single institute (id=1). Policy allows read for rows where institute_id = 1.
-- Backend/n8n uses service_role key and bypasses RLS.
CREATE POLICY institutes_select_pilot ON institutes
  FOR SELECT USING (id = 1);

CREATE POLICY uploads_select_pilot ON uploads
  FOR SELECT USING (institute_id = 1);

CREATE POLICY query_logs_select_pilot ON query_logs
  FOR SELECT USING (institute_id = 1);

-- Optional: allow insert/update for service role via default; anon has no write.
-- (Service role bypasses RLS; no policy needed for it.)

COMMENT ON TABLE institutes IS 'One row per coaching center; id = Pinecone namespace';
COMMENT ON COLUMN query_logs.institute_id IS 'FK to institutes; every row linked to an institute for multi-tenancy';
